platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.7.1

inputs:
- name: resource-template

outputs:
- name: coverage-results

run:
  path: ./resource-template/ci/scripts/unit-tests.sh