# concourse-resource-template test-this-resource pipeline.yml

#------------------------------------------------------------------------------------------
jobs:

#**********************************************
- name: job-test-concourse-resource-template
#**********************************************
  plan:
    # CONCOURSE RESOURCE TEMPLATE
    - get: concourse-resource-template-test
      trigger: true

    # RUN TASK IN REPO USING ALPINE DOCKER IMAGE
    - task: task-test-concourse-resource-template
      file: concourse-resource-template/test-resource/tasks/task-test-concourse-resource-template.yml

      # TASK SUCCESS
      on_success:
        do:
          # CONCOURSE RESOURCE TEMPLATE
          - put: concourse-resource-template-test
            params:
              param1: "Hello jeff"
              param2: "How are you?"    


#------------------------------------------------------------------------------------------
resource_types:

  - name: jeffs-resource
    type: docker-image
    source:
      repository: jeffdecola/concourse-resource-template
      tag: latest

#------------------------------------------------------------------------------------------
resources:

  - name: concourse-resource-template-test
    type: jeffs-resource
    source:
      source1: "This is the info for source 1"
      source2: "This is the info for source 2"
