#!/bin/bash
# resource-template in

# NOTE: YOU CAN REMOVE ALL THESE ECHO'S.  I FIND THEM HELPFUL

set -e              # Willexit immediate if command exits with non-zero status
set -u              # Will print message if variable not set,
#set -x             # Prints the shell commands +
set -o pipefail     # Fail on a pipline like cmd1 | cmd2 | cmd3, rather then wait

exec 3>&1           # Make stdout available as fd 3 for the result
exec 1>&2           # Redirect all output to stderr for logging

echo "IN (FETCH THE RESOURCE)"
echo ""

# Get the working directory from arg $1
WORKING_DIR=$1
echo "WORKING_DIR = $WORKING_DIR"
echo "List whats in the working directory"
ls -lat $WORKING_DIR
echo ""

# We imported tree into the build.  Not needed, but fun to know how to do it.
cd $WORKING_DIR
tree

#  INPUT **************************************************************************************
# Read stdin (which is json paramter) to file
# -M = Monochrome output
# -S = Sort order, 
# . =  get everything.
jq -M -S . < /dev/stdin | tee /tmp/input.json    # tee redirects to a file.

echo "json stdin is:"
cat /tmp/input.json
echo ""

# PARSE THE JSON FILE /tmp/input.json 
source1=$(jq -r .source.source1 < /tmp/input.json)
source2=$(jq -r .source.source2 < /tmp/input.json)
param1=$(jq -r .params.param1 < /tmp/input.json)
param2=$(jq -r .params.param2 < /tmp/input.json)
ref=$(jq -r .version.ref < /tmp/input.json)
echo "source are"
echo $source1 $source2
echo ""
echo "params are"
echo $param1 $param2
echo ""
echo "ref is"
echo $ref
echo ""

echo "pwd is"
pwd 
echo ""

echo "List whats in top directory"
ls -lat 
echo ""

# IN (FETCH THE RESOURCE) *************************************************************************
# Mimic a fetch and place a fetched.json file in the working directory that contains the following.

json_file='{
  "version": { "ref": "'$ref'" },
  "metadata": { "happy": "days" }
}'

jq -n "$json_file" > fetch.json

echo "List whats in the directory"
ls -lat 
echo ""

echo "cat fetch.json"
cat fetch.json
echo ""

monkeyname="Larry"

# OUTPUT **************************************************************************************
json_output='{
    "version":{ "ref": "'$ref'" },
    "metadata": [
        { "name": "nameofmonkey", "value": "'$monkeyname'" },
        { "name": "author", "value": "Jeff DeCola" }
    ]
}'

echo "jason output is $json_output"

# -n don't read any input at all.  Construct froms scratch.
jq -n "$json_output" >&3