# concourse-resource-template task-build-push.yml

platform: linux

# DOCKER BASE IMAGE FOR TASKS (BASED ON ALPINE, A SMALLER LINUX DISTRIBUTION)
image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.20.1

inputs:
  - name: concourse-resource-template

outputs:
  - name: dist

run:
  path: ./concourse-resource-template/ci/scripts/build-push.sh
  # args: [-debug]
