# concourse-resource-template task-readme-github-pages.yml

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.20.1

inputs:
  - name: concourse-resource-template
  - name: got-from-the-resource

#outputs:
#  - name: concourse-resource-template-updated

run:
  path: ./concourse-resource-template/test-this-resource/scripts/test-concourse-resource-template.sh
  # args: [-debug]
