# concourse-resource-template pipeline.yml

#------------------------------------------------------------------------------------------
jobs:

#**********************************************
- name: job-test-concourse-resource-template
#**********************************************
  plan:

    # GET REPO FROM GITHUB
    - get: concourse-resource-template
      trigger: true
    # CONCOURSE RESOURCE TEMPLATE
    - put: concourse-resource-template-test
      params:
        param1: "hello jeff"
        param2: "How are you?"    
    # RUN TASK IN REPO USING ALPINE DOCKER IMAGE
    - task: task-test-concourse-resource-template
      file: concourse-resource-template/test-resource/tasks/task-test-concourse-resource-template.yml

#------------------------------------------------------------------------------------------
resource_types:

  - name: jeffs-resource
    type: docker-image
    source:
      repository: jeffdecola/concourse-resource-template
      tag: latest

#------------------------------------------------------------------------------------------
resources:

  - name: concourse-resource-template
    type: git
    icon: github
    source:
      #uri: https://github.com/jeffdecola/concourse-resource-template
      uri: git@github.com:jeffdecola/concourse-resource-template.git
      branch: master
      private_key: ((git_private_key))

  - name: concourse-resource-template-test
    type: jeffs-resource
    source:
      source1: foo1
      source2: foo2
